# Control file for continuous integration testing at http://travis-ci.org/

language: c

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    # An unoptimised C99 build, for detecting non-static inline functions
    - os: linux
      compiler: gcc
      env: CFLAGS="-std=gnu99 -O0"
    - os: osx
      compiler: gcc

env:
  global:
    - HTSDIR=./htslib
    - SAMTOOLSDIR=./samtools
    - PATH=$SAMTOOLSDIR:$PATH

install:
  - .travis/clone ${HTSREPO:-git://github.com/samtools/htslib.git} $HTSDIR $TRAVIS_BRANCH
  - .travis/clone ${HTSREPO:-git://github.com/samtools/samtools.git} $SAMTOOLSDIR $TRAVIS_BRANCH

before_script:
  - (cd $SAMTOOLSDIR && autoconf && make)

script: make -e && make -e test
